# Generated by Django 3.1.3 on 2020-11-12 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanLabelColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('hex_value', models.CharField(max_length=7, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizerItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('organizeritem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organizer.organizeritem')),
                ('date', models.DateField()),
            ],
            bases=('organizer.organizeritem',),
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('organizeritem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organizer.organizeritem')),
                ('month_name', models.CharField(max_length=25)),
                ('month_number', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('year', models.IntegerField()),
            ],
            bases=('organizer.organizeritem',),
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('organizeritem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organizer.organizeritem')),
                ('week_number', models.IntegerField()),
            ],
            bases=('organizer.organizeritem',),
        ),
        migrations.CreateModel(
            name='KanbanItemLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizer.kanbanlabelcolor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KanBanItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('rollover_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('to do', 'to do'), ('doing', 'doing'), ('done', 'done')], default='to do', max_length=10)),
                ('rollover_handled', models.BooleanField(default=False)),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizer.kanbanitemlabel')),
                ('organizer_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.organizeritem')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
