# Generated by Django 3.1.3 on 2020-11-12 13:55

from django.db import migrations
from organizer.models import KanbanLabelColor
from organizer.utils import color_choice_dict


def forward(apps, schema_editor):
    for name, hex_value in color_choice_dict.items():
        if hex_value:
            labelcolor = KanbanLabelColor(
                name=name,
                hex_value=hex_value,
            )
            labelcolor.save()


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
